---
title: "HPMS Scorecard Summary"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(forcats)
library(plotly)
library(DT)
library(dplyr)
library(readr)

output_folder = 'output'
# Load the data
tbl = read_csv(file.path('..', output_folder, '_score_summary.csv')) %>%
  mutate(quality_sub = 100 * quality_sub,
         cross_sub = 100 * cross_sub)
```

## Column {data-width=600}

### Raw data

```{r}
tbl %>%
  select(state, state_num, timeliness=timely, complete, quality, total) %>%
  arrange(desc(total), state) %>%
  DT::datatable(options=list(pageLength=25))
```

## Column {data-width=400, .tabset}

### Total Scores

```{r, warning=FALSE}
tbl = tbl %>%
  mutate(state = fct_reorder(state, total, na.rm=TRUE)) %>%
  mutate(state = fct_relevel(state, as.character(state[is.na(total)])))

plt = tbl %>%
  ggplot(aes(x = state, y=total)) +
  geom_point(color='darkblue') +
  scale_y_continuous(breaks=seq(15, 45, by=5)) +
  labs(x = '',
       y = 'Score') +
  coord_flip() +
  theme_minimal()

plt %>%
  ggplotly(width=400)
```


### Score components

#### Quality vs completeness 

```{r}
plt = tbl %>%
  ggplot(aes(x = complete, y=quality)) +
  geom_text(aes(label=state), color='darkblue', alpha=0.7) +
  # geom_rug() +
  scale_x_continuous(breaks=seq(0, 16, by=2)) +
  scale_y_continuous(breaks=seq(14, 19, by = 1)) +
  theme_minimal() +
  labs(x = 'Completeness',
       y = 'Quality')

plt %>%
  ggplotly(width=400, height=300)
```

#### Quality score components

```{r}
plt = tbl %>%
  ggplot(aes(x = quality_sub, y=cross_sub)) +
  geom_text(aes(label=state), color='darkblue', alpha=0.7) +
  scale_x_continuous(breaks = seq(20, 100, by=10)) +
  scale_y_continuous(breaks = seq(80, 100, by=5)) +
  theme_minimal() +
  labs(x = 'Quality sub score',
       y = 'Cross-validation sub score')

plt %>%
  ggplotly(width=400, height=300)
```

